image: mono:5.4

before_script:
 - apt-get update
 - apt-get install -y -qq libsodium-dev fsharp

build:
 stage: build
 script:
 - mono .paket/paket.exe restore
 - pushd src/Zulib && ./build.sh && popd
 - msbuild src/zenprotocol.sln
 - cp packages/zen_secp256k1_linux/output/libsecp256k1.so /usr/lib 
 - ./run-tests
